Fatal Python error: Segmentation fault

Thread 0x000070000fb22000 (most recent call first):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 306 in wait
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 558 in wait
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 230 in _on_run
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x000070000eb1f000 (most recent call first):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 306 in wait
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 558 in wait
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 184 in _on_run
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x000070000db1c000 (most recent call first):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 302 in wait
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 558 in wait
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_timeout.py", line 43 in _on_run
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x000070000cb19000 (most recent call first):
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 209 in _read_line
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 227 in _on_run
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x000070000bb16000 (most recent call first):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 306 in wait
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/queue.py", line 179 in get
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 338 in _on_run
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00000001119d8dc0 (most recent call first):
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59 in quick_execute
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545 in call
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923 in _call_flat
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843 in _filtered_call
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829 in __call__
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 814 in _call
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780 in __call__
  File "/Users/addisonhanrattie/Desktop/BattleShip Model Creation/Battleship_Modeling/trainer.py", line 125 in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97 in _run_module_code
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265 in run_path
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267 in run_file
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430 in main
  File "/Users/addisonhanrattie/.vscode/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/__main__.py", line 45 in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194 in _run_module_as_main
